In [1]:
import cv2
import numpy as np
import pandas as pd

img11 = cv2.imread('../images/suavizante/Manzana/1.jpeg')
img12 = cv2.imread('../images/suavizante/Manzana/2.jpeg')
img13 = cv2.imread('../images/suavizante/Manzana/3.jpeg')
img14 = cv2.imread('../images/suavizante/Manzana/4.jpeg')
img15 = cv2.imread('../images/suavizante/Manzana/5.jpeg')
img16 = cv2.imread('../images/suavizante/Manzana/6.jpeg')
img17 = cv2.imread('../images/suavizante/Manzana/7.jpeg')
img18 = cv2.imread('../images/suavizante/Manzana/8.jpeg')
img19 = cv2.imread('../images/suavizante/Manzana/9.jpeg')
img21 = cv2.imread('../images/suavizante/Primavera/1.jpeg')
img22 = cv2.imread('../images/suavizante/Primavera/2.jpeg')
img23 = cv2.imread('../images/suavizante/Primavera/3.jpeg')
img24 = cv2.imread('../images/suavizante/Primavera/4.jpeg')
img25 = cv2.imread('../images/suavizante/Primavera/5.jpeg')
img26 = cv2.imread('../images/suavizante/Primavera/6.jpeg')
img27 = cv2.imread('../images/suavizante/Primavera/7.jpeg')
img28 = cv2.imread('../images/suavizante/Primavera/8.jpeg')
img29 = cv2.imread('../images/suavizante/Primavera/9.jpeg')
bordes11 = cv2.Canny(img11, 135, 150)
bordes12 = cv2.Canny(img12, 135, 150)
bordes13 = cv2.Canny(img13, 135, 150)
bordes14 = cv2.Canny(img14, 135, 150)
bordes15 = cv2.Canny(img15, 135, 150)
bordes16 = cv2.Canny(img16, 135, 150)
bordes17 = cv2.Canny(img17, 135, 150)
bordes18 = cv2.Canny(img18, 135, 150)
bordes19 = cv2.Canny(img19, 135, 150)
bordes21 = cv2.Canny(img21, 135, 150)
bordes22 = cv2.Canny(img22, 135, 150)
bordes23 = cv2.Canny(img23, 135, 150)
bordes24 = cv2.Canny(img24, 135, 150)
bordes25 = cv2.Canny(img25, 135, 150)
bordes26 = cv2.Canny(img26, 135, 150)
bordes27 = cv2.Canny(img27, 135, 150)
bordes28 = cv2.Canny(img28, 135, 150)
bordes29 = cv2.Canny(img29, 135, 150)

num_kpt = 1000
# Declaramos el objeto
orb = cv2.ORB_create(num_kpt)
# Extraemos la info de la img
# keypoint1, descriptor1 = orb.detectAndCompute(img, None)
keypoint11, descriptor11 = orb.detectAndCompute(bordes11, None)
keypoint12, descriptor12 = orb.detectAndCompute(bordes12, None)
keypoint13, descriptor13 = orb.detectAndCompute(bordes13, None)
keypoint14, descriptor14 = orb.detectAndCompute(bordes14, None)
keypoint15, descriptor15 = orb.detectAndCompute(bordes15, None)
keypoint16, descriptor16 = orb.detectAndCompute(bordes16, None)
keypoint17, descriptor17 = orb.detectAndCompute(bordes17, None)
keypoint18, descriptor18 = orb.detectAndCompute(bordes18, None)
keypoint19, descriptor19 = orb.detectAndCompute(bordes19, None)
keypoint21, descriptor21 = orb.detectAndCompute(bordes21, None)
keypoint22, descriptor22 = orb.detectAndCompute(bordes22, None)
keypoint23, descriptor23 = orb.detectAndCompute(bordes23, None)
keypoint24, descriptor24 = orb.detectAndCompute(bordes24, None)
keypoint25, descriptor25 = orb.detectAndCompute(bordes25, None)
keypoint26, descriptor26 = orb.detectAndCompute(bordes26, None)
keypoint27, descriptor27 = orb.detectAndCompute(bordes27, None)
keypoint28, descriptor28 = orb.detectAndCompute(bordes28, None)
keypoint29, descriptor29 = orb.detectAndCompute(bordes29, None)

############################################################################

df_descr11 = pd.DataFrame(descriptor11)
df_descr11.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = []; yPoints= []; angles = []; octaves = []; responses = []; sizes = []; classes = []

for kp in keypoint11:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr11['X'] = df_xPoints
df_descr11['Y'] = df_yPoints
df_descr11['Angles'] = df_angles
df_descr11['Octaves'] = df_octaves
df_descr11['Responses'] = df_responses
df_descr11['Sizes'] = df_sizes
df_descr11['Classes'] = df_classes

df_descr12 = pd.DataFrame(descriptor12)
df_descr12.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint12:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr12['X'] = df_xPoints
df_descr12['Y'] = df_yPoints
df_descr12['Angles'] = df_angles
df_descr12['Octaves'] = df_octaves
df_descr12['Responses'] = df_responses
df_descr12['Sizes'] = df_sizes
df_descr12['Classes'] = df_classes

df_descr13 = pd.DataFrame(descriptor13)
df_descr13.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint13:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr13['X'] = df_xPoints
df_descr13['Y'] = df_yPoints
df_descr13['Angles'] = df_angles
df_descr13['Octaves'] = df_octaves
df_descr13['Responses'] = df_responses
df_descr13['Sizes'] = df_sizes
df_descr13['Classes'] = df_classes

df_descr14 = pd.DataFrame(descriptor14)
df_descr14.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint14:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr14['X'] = df_xPoints
df_descr14['Y'] = df_yPoints
df_descr14['Angles'] = df_angles
df_descr14['Octaves'] = df_octaves
df_descr14['Responses'] = df_responses
df_descr14['Sizes'] = df_sizes
df_descr14['Classes'] = df_classes

df_descr15 = pd.DataFrame(descriptor15)
df_descr15.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint15:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr15['X'] = df_xPoints
df_descr15['Y'] = df_yPoints
df_descr15['Angles'] = df_angles
df_descr15['Octaves'] = df_octaves
df_descr15['Responses'] = df_responses
df_descr15['Sizes'] = df_sizes
df_descr15['Classes'] = df_classes

df_descr16 = pd.DataFrame(descriptor16)
df_descr16.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint16:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr16['X'] = df_xPoints
df_descr16['Y'] = df_yPoints
df_descr16['Angles'] = df_angles
df_descr16['Octaves'] = df_octaves
df_descr16['Responses'] = df_responses
df_descr16['Sizes'] = df_sizes
df_descr16['Classes'] = df_classes

df_descr17 = pd.DataFrame(descriptor17)
df_descr17.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint17:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr17['X'] = df_xPoints
df_descr17['Y'] = df_yPoints
df_descr17['Angles'] = df_angles
df_descr17['Octaves'] = df_octaves
df_descr17['Responses'] = df_responses
df_descr17['Sizes'] = df_sizes
df_descr17['Classes'] = df_classes

df_descr18 = pd.DataFrame(descriptor18)
df_descr18.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint18:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr18['X'] = df_xPoints
df_descr18['Y'] = df_yPoints
df_descr18['Angles'] = df_angles
df_descr18['Octaves'] = df_octaves
df_descr18['Responses'] = df_responses
df_descr18['Sizes'] = df_sizes
df_descr18['Classes'] = df_classes

df_descr19 = pd.DataFrame(descriptor19)
df_descr19.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint19:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr19['X'] = df_xPoints
df_descr19['Y'] = df_yPoints
df_descr19['Angles'] = df_angles
df_descr19['Octaves'] = df_octaves
df_descr19['Responses'] = df_responses
df_descr19['Sizes'] = df_sizes
df_descr19['Classes'] = df_classes

#----------------------------------------------------------------

df_descr21 = pd.DataFrame(descriptor21)
df_descr21.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = []; yPoints= []; angles = []; octaves = []; responses = []; sizes = []; classes = []

for kp in keypoint21:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr21['X'] = df_xPoints
df_descr21['Y'] = df_yPoints
df_descr21['Angles'] = df_angles
df_descr21['Octaves'] = df_octaves
df_descr21['Responses'] = df_responses
df_descr21['Sizes'] = df_sizes
df_descr21['Classes'] = df_classes

df_descr22 = pd.DataFrame(descriptor22)
df_descr22.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint22:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr22['X'] = df_xPoints
df_descr22['Y'] = df_yPoints
df_descr22['Angles'] = df_angles
df_descr22['Octaves'] = df_octaves
df_descr22['Responses'] = df_responses
df_descr22['Sizes'] = df_sizes
df_descr22['Classes'] = df_classes

df_descr23 = pd.DataFrame(descriptor23)
df_descr23.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint23:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr23['X'] = df_xPoints
df_descr23['Y'] = df_yPoints
df_descr23['Angles'] = df_angles
df_descr23['Octaves'] = df_octaves
df_descr23['Responses'] = df_responses
df_descr23['Sizes'] = df_sizes
df_descr23['Classes'] = df_classes

df_descr24 = pd.DataFrame(descriptor24)
df_descr24.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint24:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr24['X'] = df_xPoints
df_descr24['Y'] = df_yPoints
df_descr24['Angles'] = df_angles
df_descr24['Octaves'] = df_octaves
df_descr24['Responses'] = df_responses
df_descr24['Sizes'] = df_sizes
df_descr24['Classes'] = df_classes

df_descr25 = pd.DataFrame(descriptor25)
df_descr25.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint25:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr25['X'] = df_xPoints
df_descr25['Y'] = df_yPoints
df_descr25['Angles'] = df_angles
df_descr25['Octaves'] = df_octaves
df_descr25['Responses'] = df_responses
df_descr25['Sizes'] = df_sizes
df_descr25['Classes'] = df_classes

df_descr26 = pd.DataFrame(descriptor26)
df_descr26.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint16:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr26['X'] = df_xPoints
df_descr26['Y'] = df_yPoints
df_descr26['Angles'] = df_angles
df_descr26['Octaves'] = df_octaves
df_descr26['Responses'] = df_responses
df_descr26['Sizes'] = df_sizes
df_descr26['Classes'] = df_classes

df_descr27 = pd.DataFrame(descriptor27)
df_descr27.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint27:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr27['X'] = df_xPoints
df_descr27['Y'] = df_yPoints
df_descr27['Angles'] = df_angles
df_descr27['Octaves'] = df_octaves
df_descr27['Responses'] = df_responses
df_descr27['Sizes'] = df_sizes
df_descr27['Classes'] = df_classes

df_descr28 = pd.DataFrame(descriptor28)
df_descr28.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint28:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr28['X'] = df_xPoints
df_descr28['Y'] = df_yPoints
df_descr28['Angles'] = df_angles
df_descr28['Octaves'] = df_octaves
df_descr28['Responses'] = df_responses
df_descr28['Sizes'] = df_sizes
df_descr28['Classes'] = df_classes

df_descr29 = pd.DataFrame(descriptor29)
df_descr29.columns = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32']
xPoints = yPoints = angles = octaves = responses = sizes = classes = []

for kp in keypoint29:
  x,y = kp.pt
  xPoints.append(x)
  yPoints.append(y)
  angles.append(kp.angle)
  octaves.append(kp.octave)
  responses.append(kp.response)
  sizes.append(kp.size)
  classes.append(kp.class_id)

df_xPoints = pd.DataFrame(xPoints)
df_yPoints = pd.DataFrame(yPoints)
df_angles = pd.DataFrame(angles)
df_octaves = pd.DataFrame(octaves)
df_responses = pd.DataFrame(responses)
df_sizes = pd.DataFrame(sizes)
df_classes = pd.DataFrame(classes)

df_descr29['X'] = df_xPoints
df_descr29['Y'] = df_yPoints
df_descr29['Angles'] = df_angles
df_descr29['Octaves'] = df_octaves
df_descr29['Responses'] = df_responses
df_descr29['Sizes'] = df_sizes
df_descr29['Classes'] = df_classes

df_manzana = pd.concat([df_descr11, df_descr12, df_descr13, df_descr14, df_descr15, df_descr16, df_descr17, df_descr18, df_descr19])
suavizante_uno = np.ones(df_manzana.shape[0]) # Manzana
suavizante_dos = np.zeros(df_manzana.shape[0]) # Primavera
df_manzana['Manzana'] = pd.DataFrame(suavizante_uno)
df_manzana['Primavera'] = pd.DataFrame(suavizante_dos)

df_primavera = pd.concat([df_descr21, df_descr22, df_descr23, df_descr24, df_descr25, df_descr26, df_descr27, df_descr28, df_descr29])
suavizante_uno = np.zeros(df_primavera.shape[0]) # Manzana
suavizante_dos = np.ones(df_primavera.shape[0]) # Primavera
df_primavera['Manzana'] = pd.DataFrame(suavizante_uno)
df_primavera['Primavera'] = pd.DataFrame(suavizante_dos)
# print(df_primavera.head())
df = pd.concat([df_manzana, df_primavera])
print(df.shape)
# print(df.info())


df.to_csv('./Dataset_suavizante.csv', index=False)


(18000, 41)


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [3]:
df = pd.read_csv('Dataset_suavizante.csv')
df.shape, df.columns, df.head()

((18000, 41),
 Index(['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11',
        'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21',
        'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31',
        'D32', 'X', 'Y', 'Angles', 'Octaves', 'Responses', 'Sizes', 'Classes',
        'Manzana', 'Primavera'],
       dtype='object'),
     D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  ...  D32      X       Y  \
 0   19  250   16  186   19  159   58  248  190   12  ...  213  157.0   852.0   
 1  176  115  226   55   36   10  229  117  121  198  ...  235  502.0  1026.0   
 2  178   80   43   56    9   87   80  238  155  226  ...   94  440.0  1024.0   
 3   89   37  171  164   17   78  111   96   96  224  ...   96  201.0  1024.0   
 4  202  147   26  162  226  145   59  252  173   36  ...  155  529.0  1023.0   
 
        Angles  Octaves  Responses  Sizes  Classes  Manzana  Primavera  
 0  278.819885      0.0   0.024052   31.0     -1.0      1

In [4]:
# Varibles independientes
x = df.iloc[:, :-2].values
# print(x[0].shape)
x = pd.DataFrame(x)
x.columns = df.columns[:-2]

y = df.iloc[:, 39:].values
y = pd.DataFrame(y)
y.columns = df.columns[39:]
# print(y.shape)

# test_size toma el 20% de los datos para testing
# random_state es un número cualquiera para que siempre me genere el mismo resultado
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

x_train.shape, y_train.shape, x_test.shape, y_test.shape

((14400, 39), (14400, 2), (3600, 39), (3600, 2))

In [5]:
# Escalo los datos entre 0 y 1
x_min_max_train = preprocessing.MinMaxScaler().fit_transform(x_train)
x_min_max_test = preprocessing.MinMaxScaler().fit_transform(x_test)
x_min_max_train, x_min_max_test

(array([[0.29803922, 0.41176471, 0.10196078, ..., 0.00080321, 0.00080321,
         0.00080321],
        [0.31372549, 0.15686275, 0.60392157, ..., 0.        , 0.        ,
         0.        ],
        [0.63137255, 0.14509804, 0.34509804, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.32156863, 0.8       , 0.71764706, ..., 0.00080347, 0.0627614 ,
         0.        ],
        [0.27058824, 0.4745098 , 0.19215686, ..., 0.57831325, 0.57831325,
         0.57831325],
        [0.39215686, 0.48235294, 0.78431373, ..., 0.00082437, 0.00082437,
         0.00082437]]),
 array([[4.31372549e-02, 9.09803922e-01, 1.72549020e-01, ...,
         2.54952627e-01, 2.54952627e-01, 2.54952627e-01],
        [6.47058824e-01, 8.27450980e-01, 4.11764706e-01, ...,
         8.61929583e-04, 4.70008653e-02, 0.00000000e+00],
        [1.96078431e-02, 7.09803922e-01, 2.47058824e-01, ...,
         2.24450426e-01, 2.24450426e-01, 2.24450426e-01],
        ...,
        [9.41176471e-02, 1.41176471e

In [6]:
y_min_max_train = preprocessing.MinMaxScaler().fit_transform(y_train)
y_min_max_test = preprocessing.MinMaxScaler().fit_transform(y_test)
y_min_max_train, y_min_max_test

(array([[1., 0.],
        [1., 0.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 1.],
        [1., 0.],
        ...,
        [0., 1.],
        [1., 0.],
        [0., 1.]]))

In [7]:
# Crear los dataset
x_train1 = pd.DataFrame(x_min_max_train)
x_test1 = pd.DataFrame(x_min_max_test)
x_train1.columns = x_train.columns
x_test1.columns = x_test.columns
x_train1

D1        D2        D3        D4        D5        D6        D7  \
0      0.298039  0.411765  0.101961  0.980392  0.647059  0.678431  0.317647   
1      0.313725  0.156863  0.603922  0.737255  0.035294  0.752941  0.313725   
2      0.631373  0.145098  0.345098  0.647059  0.423529  0.043137  0.384314   
3      0.309804  0.443137  0.952941  0.266667  0.764706  0.470588  0.431373   
4      0.129412  0.705882  0.737255  0.882353  0.674510  0.176471  0.490196   
...         ...       ...       ...       ...       ...       ...       ...   
14395  0.066667  0.211765  0.192157  0.270588  0.196078  0.305882  0.388235   
14396  0.360784  0.952941  0.603922  0.701961  0.623529  0.349020  0.152941   
14397  0.321569  0.800000  0.717647  0.498039  0.662745  0.062745  0.235294   
14398  0.270588  0.474510  0.192157  0.223529  0.678431  0.674510  0.329412   
14399  0.392157  0.482353  0.784314  0.654902  0.666667  0.286275  0.086275   

             D8        D9       D10  ...       D30       D31       D32  \
0      0.517647  0.929412  0.113725  ...  0.576471  0.560784  0.007843   
1      0.278431  0.670588  0.078431  ...  0.000000  0.184314  0.039216   
2      0.478431  0.392157  0.627451  ...  0.658824  0.447059  0.501961   
3      0.062745  0.145098  0.752941  ...  0.968627  0.164706  0.078431   
4      0.247059  0.117647  0.247059  ...  0.282353  0.513725  0.827451   
...         ...       ...       ...  ...       ...       ...       ...   
14395  0.062745  0.454902  0.282353  ...  0.635294  0.027451  0.945098   
14396  0.909804  0.964706  0.862745  ...  0.231373  0.678431  0.258824   
14397  0.525490  0.427451  0.090196  ...  0.329412  0.643137  0.054902   
14398  0.607843  0.498039  0.349020  ...  0.835294  0.823529  0.325490   
14399  0.125490  0.000000  0.878431  ...  0.980392  0.117647  0.564706   

              X         Y    Angles   Octaves  Responses     Sizes   Classes  
0      0.000803  0.000803  0.000803  0.000803   0.000803  0.000803  0.000803  
1      0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  
2      0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  
3      0.225292  0.573537  0.117539  0.006426   0.000803  0.090023  0.000000  
4      0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  
...         ...       ...       ...       ...        ...       ...       ...  
14395  0.404659  0.844177  0.019104  0.001606   0.000809  0.030683  0.000000  
14396  0.000841  0.000841  0.000841  0.000841   0.000841  0.000841  0.000841  
14397  0.218656  0.708326  0.240160  0.004819   0.000803  0.062761  0.000000  
14398  0.578313  0.578313  0.578313  0.578313   0.578313  0.578313  0.578313  
14399  0.000824  0.000824  0.000824  0.000824   0.000824  0.000824  0.000824  

[14400 rows x 39 columns]

In [8]:
# Crear los dataset
y_train1 = pd.DataFrame(y_min_max_train)
y_test1 = pd.DataFrame(y_min_max_test)
y_train1.columns = y_train.columns
y_test1.columns = y_test.columns
y_train1

Manzana  Primavera
0          1.0        0.0
1          1.0        0.0
2          0.0        1.0
3          1.0        0.0
4          1.0        0.0
...        ...        ...
14395      0.0        1.0
14396      0.0        1.0
14397      0.0        1.0
14398      0.0        1.0
14399      1.0        0.0

[14400 rows x 2 columns]

In [9]:
# Se hace la transpuesta porque Normalizer trabaja con filas
x_normalizer_train = preprocessing.Normalizer().transform(x_train.T)
x_normalizer_train = x_normalizer_train.T
x_normalizer_test = preprocessing.Normalizer().transform(x_test.T)
x_normalizer_test = x_normalizer_test.T
x_normalizer_train, x_normalizer_test

(array([[ 4.87965071e-03,  6.40174687e-03,  1.48044010e-03, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.13647444e-03,  2.43876071e-03,  8.76876061e-03, ...,
         -2.23842148e-05, -2.23534294e-05, -2.23842058e-05],
        [ 1.03371548e-02,  2.25585366e-03,  5.01072035e-03, ...,
         -2.23842148e-05, -2.23534294e-05, -2.23842058e-05],
        ...,
        [ 5.26488630e-03,  1.24376796e-02,  1.04200207e-02, ...,
          7.30443078e-09,  1.72429748e-03, -2.23842058e-05],
        [ 4.43020920e-03,  7.37725115e-03,  2.79006019e-03, ...,
          1.60942505e-02,  1.60721157e-02,  1.60942440e-02],
        [ 6.42059304e-03,  7.49918919e-03,  1.13880008e-02, ...,
          5.89531848e-07,  5.88721053e-07,  5.89531611e-07]]),
 array([[ 1.40785414e-03,  2.88125020e-02,  4.93040414e-03, ...,
          1.33778070e-02,  1.33589115e-02,  1.33778016e-02],
        [ 2.11178121e-02,  2.62044738e-02,  1.17657371e-02, ...,
          3.17551081e-08,  2.42579739e

In [10]:
# Se hace la transpuesta porque Normalizer trabaja con filas
y_normalizer_train = preprocessing.Normalizer().transform(y_train.T)
y_normalizer_train = y_normalizer_train.T
y_normalizer_test = preprocessing.Normalizer().transform(y_test.T)
y_normalizer_test = y_normalizer_test.T
y_normalizer_train, y_normalizer_test

(array([[0.01177286, 0.        ],
        [0.01177286, 0.        ],
        [0.        , 0.01179741],
        ...,
        [0.        , 0.01179741],
        [0.        , 0.01179741],
        [0.01177286, 0.        ]]),
 array([[0.02366905, 0.        ],
        [0.        , 0.02347263],
        [0.02366905, 0.        ],
        ...,
        [0.        , 0.02347263],
        [0.02366905, 0.        ],
        [0.        , 0.02347263]]))

In [11]:
x_train2 = pd.DataFrame(x_normalizer_train)
x_test2 = pd.DataFrame(x_normalizer_test)
x_train2.columns = x_train.columns
x_test2.columns = x_test.columns

In [12]:
x_train2, x_test2

(             D1        D2        D3        D4        D5        D6        D7  \
 0      0.004880  0.006402  0.001480  0.015812  0.009952  0.010643  0.004942   
 1      0.005136  0.002439  0.008769  0.011891  0.000543  0.011812  0.004881   
 2      0.010337  0.002256  0.005011  0.010436  0.006514  0.000677  0.005979   
 3      0.005072  0.006889  0.013836  0.004301  0.011762  0.007383  0.006711   
 4      0.002119  0.010974  0.010705  0.014231  0.010374  0.002768  0.007626   
 ...         ...       ...       ...       ...       ...       ...       ...   
 14395  0.001092  0.003292  0.002790  0.004364  0.003016  0.004799  0.006040   
 14396  0.005907  0.014815  0.008769  0.011321  0.009590  0.005475  0.002379   
 14397  0.005265  0.012438  0.010420  0.008033  0.010193  0.000984  0.003661   
 14398  0.004430  0.007377  0.002790  0.003605  0.010435  0.010582  0.005125   
 14399  0.006421  0.007499  0.011388  0.010562  0.010254  0.004491  0.001342   
 
              D8        D9       D10  

In [13]:
x_standard_scaler_train = preprocessing.StandardScaler().fit_transform(x_train)
x_standard_scaler_test = preprocessing.StandardScaler().fit_transform(x_test)
y_standard_scaler_train = preprocessing.StandardScaler().fit_transform(y_train)
y_standard_scaler_test = preprocessing.StandardScaler().fit_transform(y_test)
x_train3 = pd.DataFrame(x_standard_scaler_train)
x_test3 = pd.DataFrame(x_standard_scaler_test)
x_train3.columns = x_train.columns
x_test3.columns = x_test.columns
y_train3 = pd.DataFrame(y_standard_scaler_train)
y_test3 = pd.DataFrame(y_standard_scaler_test)
y_train3.columns = y_train.columns
y_test3.columns = y_test.columns
# estandarizado = (X - media) / std

x_train3, x_test3

(             D1        D2        D3        D4        D5        D6        D7  \
 0     -0.470943 -0.164609 -1.374467  2.067073  0.652880  0.804891 -0.590520   
 1     -0.414041 -1.078326  0.372691  1.123259 -1.422875  1.061964 -0.605751   
 2      0.738222 -1.120498 -0.528187  0.773135 -0.105569 -1.386991 -0.331590   
 3     -0.428267 -0.052151  1.587512 -0.703478  1.052063  0.087794 -0.148816   
 4     -1.082638  0.889681  0.836780  1.686503  0.746023 -0.926967  0.079652   
 ...         ...       ...       ...       ...       ...       ...       ...   
 14395 -1.310246 -0.881526 -1.060525 -0.688255 -0.877324 -0.480472 -0.316359   
 14396 -0.243336  1.775284  0.372691  0.986254  0.573043 -0.331641 -1.230230   
 14397 -0.385590  1.227053  0.768532  0.194668  0.706104 -1.319341 -0.910375   
 14398 -0.570521  0.060306 -1.060525 -0.870928  0.759329  0.791361 -0.544827   
 14399 -0.129532  0.088421  1.000576  0.803580  0.719410 -0.548123 -1.489160   
 
              D8        D9       D10  

In [14]:
x_robust_scaler_train = preprocessing.RobustScaler().fit_transform(x_train)
x_robust_scaler_test = preprocessing.RobustScaler().fit_transform(x_test)
# x_robust_scaler_train = preprocessing.RobustScaler().fit_transform(y_train)
# x_robust_scaler_test = preprocessing.RobustScaler().fit_transform(y_test)
x_train4 = pd.DataFrame(x_robust_scaler_train)
x_test4 = pd.DataFrame(x_robust_scaler_test)
x_train4.columns = x_train.columns
x_test4.columns = x_test.columns

x_train4, x_test4

# estandarizado = (X - rango_intercuartílico) / std

(             D1        D2        D3        D4        D5        D6        D7  \
 0     -0.191589 -0.086614 -0.842742  1.442308  0.381679  0.503704 -0.221154   
 1     -0.154206 -0.598425  0.189516  0.846154 -0.809160  0.644444 -0.230769   
 2      0.602804 -0.622047 -0.342742  0.625000 -0.053435 -0.696296 -0.057692   
 3     -0.163551 -0.023622  0.907258 -0.307692  0.610687  0.111111  0.057692   
 4     -0.593458  0.503937  0.463710  1.201923  0.435115 -0.444444  0.201923   
 ...         ...       ...       ...       ...       ...       ...       ...   
 14395 -0.742991 -0.488189 -0.657258 -0.298077 -0.496183 -0.200000 -0.048077   
 14396 -0.042056  1.000000  0.189516  0.759615  0.335878 -0.118519 -0.625000   
 14397 -0.135514  0.692913  0.423387  0.259615  0.412214 -0.659259 -0.423077   
 14398 -0.257009  0.039370 -0.657258 -0.413462  0.442748  0.496296 -0.192308   
 14399  0.032710  0.055118  0.560484  0.644231  0.419847 -0.237037 -0.788462   
 
              D8        D9       D10  

In [15]:
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)

In [16]:
x_train3.shape, y_train3.shape

((14400, 39), (14400, 2))

In [17]:
x_train3.to_csv('./Dataset_x_train_suavizante.csv', index=False)
x_test3.to_csv('./Dataset_x_test_suavizante.csv', index=False)
y_train3.to_csv('./Dataset_y_train_suavizante.csv', index=False)
y_test3.to_csv('./Dataset_y_test_suavizante.csv', index=False)