In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [27]:
df = pd.read_csv('../Dataset_suavizante.csv')
df.shape, df.columns, df.head()

((18000, 40),
 Index(['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11',
        'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21',
        'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31',
        'D32', 'X', 'Y', 'Angles', 'Octaves', 'Responses', 'Sizes', 'Classes',
        'Tipo'],
       dtype='object'),
     D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  ...  D31  D32      X   
 0   19  250   16  186   19  159   58  248  190   12  ...   11  213  157.0  \
 1  176  115  226   55   36   10  229  117  121  198  ...   86  235  502.0   
 2  178   80   43   56    9   87   80  238  155  226  ...   94   94  440.0   
 3   89   37  171  164   17   78  111   96   96  224  ...    3   96  201.0   
 4  202  147   26  162  226  145   59  252  173   36  ...  175  155  529.0   
 
         Y      Angles  Octaves  Responses  Sizes  Classes  Tipo  
 0   852.0  278.819885      0.0   0.024052   31.0     -1.0   1.0  
 1  1026.0  313.160858      0.

In [30]:
# Varibles independientes
x = df.iloc[:, :-1].values
# print(x[0].shape)
x = pd.DataFrame(x)
x.columns = df.columns[:-1]

y = df.iloc[:, 39].values
# print(y.shape)

# test_size toma el 20% de los datos para testing
# random_state es un número cualquiera para que siempre me genere el mismo resultado
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

x_train.shape, y_train.shape, x_test.shape, y_test.shape
x_train

D1     D2     D3     D4     D5     D6     D7     D8     D9    D10   
2465    76.0  105.0   26.0  250.0  165.0  173.0   81.0  132.0  237.0   29.0  \
8461    80.0   40.0  154.0  188.0    9.0  192.0   80.0   71.0  171.0   20.0   
13734  161.0   37.0   88.0  165.0  108.0   11.0   98.0  122.0  100.0  160.0   
965     79.0  113.0  243.0   68.0  195.0  120.0  110.0   16.0   37.0  192.0   
4615    33.0  180.0  188.0  225.0  172.0   45.0  125.0   63.0   30.0   63.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9225    17.0   54.0   49.0   69.0   50.0   78.0   99.0   16.0  116.0   72.0   
13123   92.0  243.0  154.0  179.0  159.0   89.0   39.0  232.0  246.0  220.0   
9845    82.0  204.0  183.0  127.0  169.0   16.0   60.0  134.0  109.0   23.0   
10799   69.0  121.0   49.0   57.0  173.0  172.0   84.0  155.0  127.0   89.0   
2732   100.0  123.0  200.0  167.0  170.0   73.0   22.0   32.0    0.0  224.0   

       ...    D30    D31    D32           X            Y      Angles   
2465   ...  147.0  143.0    2.0    0.000000     0.000000    0.000000  \
8461   ...    0.0   47.0   10.0   -1.000000    -1.000000   -1.000000   
13734  ...  168.0  114.0  128.0   -1.000000    -1.000000   -1.000000   
965    ...  247.0   42.0   20.0  279.488190   713.053162  145.335907   
4615   ...   72.0  131.0  211.0   -1.000000    -1.000000   -1.000000   
...    ...    ...    ...    ...         ...          ...         ...   
9225   ...  162.0    7.0  241.0  502.800018  1050.000000   22.785049   
13123  ...   59.0  173.0   66.0    0.046980     0.046980    0.046980   
9845   ...   84.0  164.0   14.0  271.226959   880.865479  297.999420   
10799  ...  213.0  210.0   83.0  719.000000   719.000000  719.000000   
2732   ...  250.0   30.0  144.0    0.026337     0.026337    0.026337   

          Octaves   Responses       Sizes     Classes  
2465     0.000000    0.000000    0.000000    0.000000  
8461    -1.000000   -1.000000   -1.000000   -1.000000  
13734   -1.000000   -1.000000   -1.000000   -1.000000  
965      7.000000    0.000286  111.078636   -1.000000  
4615    -1.000000   -1.000000   -1.000000   -1.000000  
...           ...         ...         ...         ...  
9225     1.000000    0.007445   37.200001   -1.000000  
13123    0.046980    0.046980    0.046980    0.046980  
9845     5.000000    0.000326   77.137939   -1.000000  
10799  719.000000  719.000000  719.000000  719.000000  
2732     0.026337    0.026337    0.026337    0.026337  

[14400 rows x 39 columns]

In [31]:
# Escalo los datos entre 0 y 1
x_min_max_train = preprocessing.MinMaxScaler().fit_transform(x_train)
x_min_max_test = preprocessing.MinMaxScaler().fit_transform(x_test)
# x_min_max_train, x_min_max_test

In [32]:
y_min_max_train = preprocessing.MinMaxScaler().fit_transform(y_train.reshape(-1, 1)) # Se le da la forma para que se pueda escalar
y_min_max_test = preprocessing.MinMaxScaler().fit_transform(y_test.reshape(-1, 1))
y_min_max_train, y_min_max_test

(array([[0.],
        [0.],
        [1.],
        ...,
        [1.],
        [1.],
        [0.]]),
 array([[0.],
        [1.],
        [0.],
        ...,
        [1.],
        [0.],
        [1.]]))

In [33]:
# Crear los dataset
x_train1 = pd.DataFrame(x_min_max_train)
x_test1 = pd.DataFrame(x_min_max_test)
x_train1.columns = x_train.columns
x_test1.columns = x_test.columns
x

D1     D2     D3     D4     D5     D6     D7     D8     D9    D10   
0       19.0  250.0   16.0  186.0   19.0  159.0   58.0  248.0  190.0   12.0  \
1      176.0  115.0  226.0   55.0   36.0   10.0  229.0  117.0  121.0  198.0   
2      178.0   80.0   43.0   56.0    9.0   87.0   80.0  238.0  155.0  226.0   
3       89.0   37.0  171.0  164.0   17.0   78.0  111.0   96.0   96.0  224.0   
4      202.0  147.0   26.0  162.0  226.0  145.0   59.0  252.0  173.0   36.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
17995   72.0   32.0   25.0   96.0   32.0   76.0   80.0   18.0   32.0    8.0   
17996   33.0  177.0   24.0   91.0  201.0  149.0  145.0   79.0   86.0   21.0   
17997  161.0  232.0   40.0   27.0   93.0  197.0  195.0  206.0  199.0   68.0   
17998  106.0  148.0   45.0  126.0   73.0   93.0   21.0   61.0  184.0   95.0   
17999  188.0   33.0  208.0  124.0  201.0   81.0   86.0  232.0  147.0  182.0   

       ...    D30    D31    D32           X            Y      Angles   
0      ...    7.0   11.0  213.0  157.000000   852.000000  278.819885  \
1      ...  190.0   86.0  235.0  502.000000  1026.000000  313.160858   
2      ...   52.0   94.0   94.0  440.000000  1024.000000   87.118973   
3      ...  162.0    3.0   96.0  201.000000  1024.000000  203.037659   
4      ...  135.0  175.0  155.0  529.000000  1023.000000  258.042877   
...    ...    ...    ...    ...         ...          ...         ...   
17995  ...  128.0   15.0   35.0  479.000000   479.000000  479.000000   
17996  ...    0.0  234.0  138.0  292.234039   292.234039  292.234039   
17997  ...    8.0  114.0  234.0    0.000000     0.000000    0.000000   
17998  ...   68.0  150.0  122.0    0.022257     0.022257    0.022257   
17999  ...  126.0  110.0    2.0   31.000000    31.000000   31.000000   

          Octaves   Responses       Sizes     Classes  
0        0.000000    0.024052   31.000000   -1.000000  
1        0.000000    0.024456   31.000000   -1.000000  
2        0.000000    0.024984   31.000000   -1.000000  
3        0.000000    0.042618   31.000000   -1.000000  
4        0.000000    0.035031   31.000000   -1.000000  
...           ...         ...         ...         ...  
17995  479.000000  479.000000  479.000000  479.000000  
17996  292.234039  292.234039  292.234039  292.234039  
17997    0.000000    0.000000    0.000000    0.000000  
17998    0.022257    0.022257    0.022257    0.022257  
17999   31.000000   31.000000   31.000000   31.000000  

[18000 rows x 39 columns]

In [34]:
# Se hace la transpuesta porque Normalizer trabaja con filas
x_normalizer_train = preprocessing.Normalizer().transform(x_train.T)
x_normalizer_train = x_normalizer_train.T
x_normalizer_test = preprocessing.Normalizer().transform(x_test.T)
x_normalizer_test = x_normalizer_test.T
x_normalizer_train, x_normalizer_test

(array([[ 4.87965071e-03,  6.40174687e-03,  1.48044010e-03, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.13647444e-03,  2.43876071e-03,  8.76876061e-03, ...,
         -2.23842148e-05, -2.23534294e-05, -2.23842058e-05],
        [ 1.03371548e-02,  2.25585366e-03,  5.01072035e-03, ...,
         -2.23842148e-05, -2.23534294e-05, -2.23842058e-05],
        ...,
        [ 5.26488630e-03,  1.24376796e-02,  1.04200207e-02, ...,
          7.30443078e-09,  1.72429748e-03, -2.23842058e-05],
        [ 4.43020920e-03,  7.37725115e-03,  2.79006019e-03, ...,
          1.60942505e-02,  1.60721157e-02,  1.60942440e-02],
        [ 6.42059304e-03,  7.49918919e-03,  1.13880008e-02, ...,
          5.89531848e-07,  5.88721053e-07,  5.89531611e-07]]),
 array([[ 1.40785414e-03,  2.88125020e-02,  4.93040414e-03, ...,
          1.33778070e-02,  1.33589115e-02,  1.33778016e-02],
        [ 2.11178121e-02,  2.62044738e-02,  1.17657371e-02, ...,
          3.17551081e-08,  2.42579739e

In [36]:
# Se hace la transpuesta porque Normalizer trabaja con filas
# y_normalizer_train = preprocessing.Normalizer().transform(y_train.T)
# y_normalizer_train = y_normalizer_train.T
# y_normalizer_test = preprocessing.Normalizer().transform(y_test.T)
# y_normalizer_test = y_normalizer_test.T
# y_normalizer_train, y_normalizer_test

In [37]:
x_train2 = pd.DataFrame(x_normalizer_train)
x_test2 = pd.DataFrame(x_normalizer_test)
x_train2.columns = x_train.columns
x_test2.columns = x_test.columns

In [38]:
x_train2, x_test2

(             D1        D2        D3        D4        D5        D6        D7   
 0      0.004880  0.006402  0.001480  0.015812  0.009952  0.010643  0.004942  \
 1      0.005136  0.002439  0.008769  0.011891  0.000543  0.011812  0.004881   
 2      0.010337  0.002256  0.005011  0.010436  0.006514  0.000677  0.005979   
 3      0.005072  0.006889  0.013836  0.004301  0.011762  0.007383  0.006711   
 4      0.002119  0.010974  0.010705  0.014231  0.010374  0.002768  0.007626   
 ...         ...       ...       ...       ...       ...       ...       ...   
 14395  0.001092  0.003292  0.002790  0.004364  0.003016  0.004799  0.006040   
 14396  0.005907  0.014815  0.008769  0.011321  0.009590  0.005475  0.002379   
 14397  0.005265  0.012438  0.010420  0.008033  0.010193  0.000984  0.003661   
 14398  0.004430  0.007377  0.002790  0.003605  0.010435  0.010582  0.005125   
 14399  0.006421  0.007499  0.011388  0.010562  0.010254  0.004491  0.001342   
 
              D8        D9       D10  

In [40]:
x_standard_scaler_train = preprocessing.StandardScaler().fit_transform(x_train)
x_standard_scaler_test = preprocessing.StandardScaler().fit_transform(x_test)
# x_standard_scaler_train = preprocessing.StandardScaler().fit_transform(y_train)
# x_standard_scaler_test = preprocessing.StandardScaler().fit_transform(y_test)
x_train3 = pd.DataFrame(x_standard_scaler_train)
x_test3 = pd.DataFrame(x_standard_scaler_test)
x_train3.columns = x_train.columns
x_test3.columns = x_test.columns
# estandarizado = (X - media) / std

x_train3, x_test3

(             D1        D2        D3        D4        D5        D6        D7   
 0     -0.470943 -0.164609 -1.374467  2.067073  0.652880  0.804891 -0.590520  \
 1     -0.414041 -1.078326  0.372691  1.123259 -1.422875  1.061964 -0.605751   
 2      0.738222 -1.120498 -0.528187  0.773135 -0.105569 -1.386991 -0.331590   
 3     -0.428267 -0.052151  1.587512 -0.703478  1.052063  0.087794 -0.148816   
 4     -1.082638  0.889681  0.836780  1.686503  0.746023 -0.926967  0.079652   
 ...         ...       ...       ...       ...       ...       ...       ...   
 14395 -1.310246 -0.881526 -1.060525 -0.688255 -0.877324 -0.480472 -0.316359   
 14396 -0.243336  1.775284  0.372691  0.986254  0.573043 -0.331641 -1.230230   
 14397 -0.385590  1.227053  0.768532  0.194668  0.706104 -1.319341 -0.910375   
 14398 -0.570521  0.060306 -1.060525 -0.870928  0.759329  0.791361 -0.544827   
 14399 -0.129532  0.088421  1.000576  0.803580  0.719410 -0.548123 -1.489160   
 
              D8        D9       D10  

In [41]:
x_robust_scaler_train = preprocessing.RobustScaler().fit_transform(x_train)
x_robust_scaler_test = preprocessing.RobustScaler().fit_transform(x_test)
# x_robust_scaler_train = preprocessing.RobustScaler().fit_transform(y_train)
# x_robust_scaler_test = preprocessing.RobustScaler().fit_transform(y_test)
x_train4 = pd.DataFrame(x_robust_scaler_train)
x_test4 = pd.DataFrame(x_robust_scaler_test)
x_train4.columns = x_train.columns
x_test4.columns = x_test.columns

x_train4, x_test4

# estandarizado = (X - rango_intercuartílico) / std

(             D1        D2        D3        D4        D5        D6        D7   
 0     -0.191589 -0.086614 -0.842742  1.442308  0.381679  0.503704 -0.221154  \
 1     -0.154206 -0.598425  0.189516  0.846154 -0.809160  0.644444 -0.230769   
 2      0.602804 -0.622047 -0.342742  0.625000 -0.053435 -0.696296 -0.057692   
 3     -0.163551 -0.023622  0.907258 -0.307692  0.610687  0.111111  0.057692   
 4     -0.593458  0.503937  0.463710  1.201923  0.435115 -0.444444  0.201923   
 ...         ...       ...       ...       ...       ...       ...       ...   
 14395 -0.742991 -0.488189 -0.657258 -0.298077 -0.496183 -0.200000 -0.048077   
 14396 -0.042056  1.000000  0.189516  0.759615  0.335878 -0.118519 -0.625000   
 14397 -0.135514  0.692913  0.423387  0.259615  0.412214 -0.659259 -0.423077   
 14398 -0.257009  0.039370 -0.657258 -0.413462  0.442748  0.496296 -0.192308   
 14399  0.032710  0.055118  0.560484  0.644231  0.419847 -0.237037 -0.788462   
 
              D8        D9       D10  